// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxthdqanawtfneqlhfzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dGhkcWFuYXd0Zm5lcWxoZnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzODE4NDMsImV4cCI6MjA1Mzk1Nzg0M30.I0fdY6ouIN511eFogZqQDf8VwseJ2tepqCmpW9uvCjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);